FROM redhat/ubi9:9.4

USER root

# Install Java
RUN dnf update -y && dnf install java-21-openjdk -y

# Install Trivy
RUN rpm -ivh https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.rpm

# Install Trufflehog
RUN curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

# Install Python 12, Syft, checkov, Cosign, Bandit, Semgrep
RUN dnf install python3.12 -y && dnf install python3.12-pip -y && pip3.12 install semgrep \
&& curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin \
&& pip3.12 install checkov && curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64" \
&& mv cosign-linux-amd64 /usr/local/bin/cosign && chmod +x /usr/local/bin/cosign \
&& pip3.12 install bandit

# Install Docker CLI
COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin/



