pipeline{
    agent{
        node {
            label "node"
        }
    }
    stages{
        stage("Verify Branch"){
            steps{
                echo "$GIT_BRANCH"
            }
        }
        stage("Docker Images"){
            steps{
                sh(script: 'docker images && whoami')
            }
        }
}
}
