services:
  jenkins:
    image: 'zazathomas/jenkins:jdk21'
    container_name: jenkins
    restart: unless-stopped
    environment:
      DOCKER_HOST: 'tcp://docker:2376'
      DOCKER_CERT_PATH: '/certs/client'
      DOCKER_TLS_VERIFY: 1
    ports:
      - '9999:8080'
      - '50000:50000'
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client:ro
    networks:
     - jenkins
     - proxy
  socat:
    restart: unless-stopped
    ports:
        - 127.0.0.1:2376:2375
    networks:
        - jenkins
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    image: alpine/socat:1.8.0.0
    container_name: socat-proxy
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock

networks:
  jenkins:
    external: true
  proxy:
    external: true

